export const ROUTES = {
  HOME: "/",
  DOCS: "/docs",
  DOCS_INSTALLATION: "/docs/installation",
  THEMING: "/theming",
  SHOWCASES: "/showcases",
  
  ACCORDION: "/accordion",
  ALERT: "/alert",
  ARTBOARD: "/artboard",
  AVATAR: "/avatar",
  BACKGROUND: "/background",
  BADGE: "/badge",
  BREADCRUMB: "/breadcrumb",
  BROWSER_MOCKUP: "/browsermockup",
  BUTTON: "/button",
  CALENDAR: "/calendar",
  CARD: "/card",
  CAROUSEL: "/carousel",
  CHAT_BUBBLE: "/chat-bubble",
  CHECKBOX: "/checkbox",
  CODE_MOCKUP: "/codemockup",
  COLLAPSE: "/collapse",
  COPY_BUTTON: "/copy-button",
  COUNTDOWN: "/countdown",
  DIFF: "/diff",
  DIVIDER: "/divider",
  DOCK: "/dock",
  DRAWER: "/drawer",
  DROPDOWN: "/dropdown",
  FILE_INPUT: "/file-input",
  FLEX: "/flex",
  FOOTER: "/footer",
  FORM: "/form",
  GRID: "/grid",
  HERO: "/hero",
  ICON: "/icon",
  INDICATOR: "/indicator",
  INPUT: "/input",
  JOIN: "/join",
  KBD: "/kbd",
  LINK: "/link",
  LOADING: "/loading",
  MASK: "/mask",
  MENU: "/menu",
  MODAL: "/modal",
  NAVBAR: "/navbar",
  PAGINATION: "/pagination",
  PHONEMOCKUP: "/phonemockup",
  PROGRESS: "/progress",
  RADIAL_PROGRESS: "/radial-progress",
  RADIO: "/radio",
  RANGE: "/range",
  RATING: "/rating",
  SELECT: "/select",
  SIDENAV: "/sidenav",
  SKELETON: "/skeleton",
  STACK: "/stack",
  STATS: "/stats",
  STEPS: "/steps",
  SVG_BACKGROUND: "/svg-background",
  SWAP: "/swap",
  TABLE: "/table",
  TABS: "/tabs",
  TEXTAREA: "/textarea",
  TIMELINE: "/timeline",
  TOAST: "/toast",
  TOGGLE: "/toggle",
  TOOLTIP: "/tooltip",
  WINDOW_MOCKUP: "/windowmockup",
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RouteValue = typeof ROUTES[RouteKey];

export const getRoute = (key: RouteKey): RouteValue => ROUTES[key];

export const isValidRoute = (path: string): boolean => 
  Object.values(ROUTES).includes(path as RouteValue);

export const EXTERNAL_ROUTES = {
  GITHUB: "https://github.com/pathscale/ui",
  GITHUB_DISCUSSIONS: "https://github.com/pathscale/ui/discussions",
  DISCORD: "https://discord.gg/pathscale",
} as const;