export const ROUTES = {
  HOME: "/",
  DOCS: "/docs",
  DOCS_INSTALLATION: "/docs/installation",
  DOCS_LAYOUTS: "/docs/layouts",
  DOCS_USAGE: "/docs/usage",
  THEMING: "/theming",
  SHOWCASES: "/showcases",
  ACCORDION: "/accordion",
  ALERT: "/alert",
  AUTH_POWERED_BY: "/auth-powered-by",
  AVATAR: "/avatar",
  BADGE: "/badge",
  BREADCRUMB: "/breadcrumb",
  BUTTON: "/button",
  CALENDAR: "/calendar",
  CARD: "/card",
  CHAT_BUBBLE: "/chat-bubble",
  CHECKBOX: "/checkbox",
  COLOR_PICKER: "/color-picker",
  COLLAPSIBLE: "/collapsible",
  DRAWER: "/drawer",
  DROPDOWN: "/dropdown",
  EMPTY: "/empty",
  FIELDSET: "/fieldset",
  FILE_INPUT: "/file-input",
  FLEX: "/flex",
  DOCK: "/dock",
  FOOTER: "/footer",
  FORM: "/form",
  FORM_ACTIONS: "/form-actions",
  GLASS_PANEL: "/glass-panel",
  GLOW_CARD: "/glow-card",
  GRID: "/grid",
  ICON: "/icon",
  INPUT: "/input",
  JOIN: "/join",
  KBD: "/kbd",
  LINK: "/link",
  MENU: "/menu",
  DIALOG: "/dialog",
  NAVBAR: "/navbar",
  NOISE_BACKGROUND: "/noise-background",
  PAGINATION: "/pagination",
  PROGRESS: "/progress",
  RADIAL_PROGRESS: "/radial-progress",
  RADIO: "/radio",
  RADIO_GROUP: "/radio-group",
  SELECT: "/select",
  SEPARATOR: "/separator",
  SKELETON: "/skeleton",
  SLIDER: "/slider",
  SPINNER: "/spinner",
  DATA_GRID: "/data-grid",
  TABLE: "/table",
  TABS: "/tabs",
  TEXTAREA: "/textarea",
  TOAST: "/toast",
  SWITCH: "/switch",
  TOOLTIP: "/tooltip",
  VIDEO_PREVIEW: "/video-preview",
  COVERAGE: "/coverage",
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RouteValue = typeof ROUTES[RouteKey];

export const getRoute = (key: RouteKey): RouteValue => ROUTES[key];

export const isValidRoute = (path: string): boolean =>
  Object.values(ROUTES).includes(path as RouteValue);

export const EXTERNAL_ROUTES = {
  GITHUB: "https://github.com/pathscale/ui",
  GITHUB_DISCUSSIONS: "https://github.com/pathscale/ui/discussions",
  UI_USAGE_DOC: "https://github.com/pathscale/ui/blob/master/docs/ui-usage.md",
  SOLID_LAYOUTS: "https://github.com/pathscale/solid-layouts",
  DISCORD: "https://discord.gg/pathscale",
} as const;
